/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DiscussionForum;

import static DiscussionForum.DiscussionPanel_Server.ServerName;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rakesh
 */
public class DiscussionPanel_Client extends javax.swing.JFrame {
public static String ClientName =""; 
public static String IPAddress =""; 
    
                    //// Client Variables
                public static Socket s_Client;
                public static BufferedReader kb_Client;
                public static PrintStream ps_Client;
                public static BufferedReader ser_Client;
                public static String name_Client;

    /**
     * Creates new form DiscussionPanel_Client
     */
    public DiscussionPanel_Client() {
        initComponents();
        
        
        
        
        
        ClientStart();
        
    }

     public void ClientStart()
    {
                try {
                    s_Client=new Socket(IPAddress,102);
                    kb_Client=new BufferedReader(new InputStreamReader(System.in));
                    ps_Client=new PrintStream(s_Client.getOutputStream());
                    ser_Client=new BufferedReader(new InputStreamReader(s_Client.getInputStream()));
                    //System.out.print("Please Enter Your Name:");
                    //name=kb.readLine();
                    name_Client=ClientName;
                    String str1,str2;
                    ps_Client.println(name_Client);
                    System.out.print("You Are Now Connected To "+ser_Client.readLine()+" (enjoy typing...)");
                    //jTextArea1.setText("You Are Now Connected To "+ser_Client.readLine()+" (enjoy typing...));
                    System.out.print(name_Client+">:");
                    while(!(str1=kb_Client.readLine()).equals("exit"))
                    {
                            ps_Client.println(name_Client+">:"+str1);
                            if (!(str2=ser_Client.readLine()).equals(""))
                            {
                                    System.out.println(str2);
                                    str2="";
                            }

                            System.out.print(name_Client+">:");

                    }
                    kb_Client.close();
                    ps_Client.close();
                    ser_Client.close();
                } catch (UnknownHostException ex) {
                    Logger.getLogger(DiscussionPanel_Server.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(DiscussionPanel_Server.class.getName()).log(Level.SEVERE, null, ex);
                }

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 450));
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 710, 290);

        jLabel1.setText("Enter here");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 360, 60, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(81, 348, 560, 60);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(647, 348, 73, 60);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 3, 55, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String text = jTextField1.getText();

        jTextArea1.append(text);
        jTextArea1.append("\n");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChatForum.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String ip, String name) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        ClientName = name;
        IPAddress = ip;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscussionPanel_Client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
