/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se_java;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rakesh
 */
public class DiscussionPanel extends javax.swing.JFrame {


    /**
     * Creates new form DiscussionPanel
     */
    public DiscussionPanel() throws ClassNotFoundException, SQLException {
        initComponents();

        
        ///////////////////////////////////////////////
        
        try
        {
            if(new DBConnection().DBConnection()){
             
             File file = new File("write.txt"); 
             if(file.exists())
             {    
                 Scanner s=new Scanner(file);
                 while(s.hasNext())
                 {
                     String temp=s.nextLine();
                     System.out.println(""+temp);
                     if(temp.equals("") || temp.equals(null))
                     {
                         
                     }    
                     else
                     new DBConnection().StoreinForum(temp);
                 }
               
                FileOutputStream fop =fop = new FileOutputStream(file);
                String content="";
                byte[] contentInBytes = content.getBytes();
                fop.write(contentInBytes);
            
             } 
            }
            
        }
        catch(Exception e)
        {
            
        }

        /////////////////////////////////////////////////////////
        try
        {

        String forum = new DBConnection().searchInForum();
        jTextArea1.setText("");
        jTextArea1.append(forum);
        }
        catch(Exception e)
        {
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 450));
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 710, 290);

        jLabel1.setText("Enter here");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 360, 60, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(81, 348, 560, 60);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(647, 348, 73, 60);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 3, 55, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String t="";
        try {      
            // TODO add your handling code here:
            String text = jTextField1.getText();
            String computername = null;
        try 
        {        
            computername = InetAddress.getLocalHost().getHostName();
        } 
        catch (UnknownHostException ex) 
        {
            Logger.getLogger(DiscussionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println(computername);
            //jTextArea1.append(computername+" :- "+text+"\n");
            String discussionString = "";  
            discussionString = computername+" :- "+text;  
            
            
        try 
        {          
            if(!new DBConnection().DBConnection()){
            
                 File file = new File("write.txt");
                 
                 Scanner sc=new Scanner(file);
                 String temp="";
                 while(sc.hasNext())
                     temp+=sc.nextLine()+"\n";
                 temp+=discussionString+"\n";
                  FileWriter f = new FileWriter(new File("write.txt"));
                 //FileOutputStream fop=new FileOutputStream("write.txt");
                  System.out.print (temp);
                f.write(temp);
                f.close();
                 System.out.println("Done");
                 JOptionPane.showMessageDialog(null,"No Internet Connection-- Your Question will be Posted when connection establishes");
              
        }
            else{
               File file = new File("write.txt"); 
             if(file.exists()){
                 
                 Scanner s=new Scanner(file);
                 while(s.hasNext()){
                  
                     String temp=s.nextLine();
                     System.out.println(""+temp);
                     if(temp.equals("") || temp.equals(null))
                     {
                         
                     }    
                     else
                     new DBConnection().StoreinForum(temp);
                 }
                 
                FileOutputStream fop =fop = new FileOutputStream(file);
                String content="";
                byte[] contentInBytes = content.getBytes();
                fop.write(contentInBytes);
                
                
             }   
                new DBConnection().StoreinForum(discussionString);
             
            }
        } 
        
        catch(Exception  ex) 
        {
            
           
        }
        
        
         
            String forumData = new DBConnection().searchInForum();
            jTextArea1.setText("");
            jTextArea1.append(forumData);
            jTextField1.setText("");
    } 
    catch (ClassNotFoundException | SQLException ex) 
    {
        Logger.getLogger(DiscussionPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String []args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscussionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DiscussionPanel().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DiscussionPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DiscussionPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
