/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se_java;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Rakesh
 */
public class ShowVideos extends javax.swing.JFrame {

    /**
     * Creates new form ShowVideos
     */
    final java.util.List<JButton> buttons;
    
//    public ShowVideos() {
//        
//        
//        
//        
//    }
    public ShowVideos( Hashtable  hash ) throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException  
    {  
        initComponents();
        System.out.println("Testing 123");
        //super("PCS Videos");   
    //    JFrame.setDefaultLookAndFeelDecorated(true);
        
      //  setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        setLocationRelativeTo(null);
        int numberOfButtons = hash.size();
        Container pane = getContentPane();
        setLayout(new BorderLayout());
       // JLabel background = new JLabel(new ImageIcon("‪C:\\Users\\Rakesh\\Desktop\\ron0a.jpg"));
        //add(background);
        
       //pane.setBackground(Color.yellow);
       // pane.
       
       
       jLabel1.setLayout( new FlowLayout() );   
        buttons = new ArrayList<>( numberOfButtons );                   
        for ( int i = 1; i <= numberOfButtons; i++ )  
        {  
            System.out.println(hash.get(i));
            String temp = (String) hash.get(i);
            String TempFinal;
            TempFinal = temp.substring(temp.indexOf("os/")+3);
            //JButton button = new JButton( new SomeAction( "Video" , i ,hash)  );  
            
            JButton button = new JButton( new SomeAction( "" ,TempFinal)  );
            
            DBConnection image = new DBConnection();
         //   image.GetImage();
            
          //  byte[] imagedata = image.GetImage((String) hash.get(i));
            //java.awt.Image img = Toolkit.getDefaultToolkit().createImage(imagedata);
       //     ImageIcon icon =new ImageIcon(img);
//JLabel lPhoto = new JLabel(icon) ; 
           // button.setIcon(icon);
            button.setPreferredSize(new Dimension(100, 100));
            jLabel1.add( button );  
            // Remember buttons in collection, we might need to access them sometime  
            buttons.add( button );  
        }  
        
        
        pack();  
    }  
  
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(751, 451));
        getContentPane().setLayout(null);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 70, 100, 23);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("          PCS   Videos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corporate_law.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 750, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage.main(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final Hashtable  hash) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowVideos(hash).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ShowVideos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ShowVideos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ShowVideos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowVideos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
